### ISSUE TITLE
Introduce BASIC authorization to API

### ISSUE THREAD

**Issue by Aemilivs** [Aemilivs/2201-SAD-Bot-Trader#3]

**Comment by Sol-Mane** [comment]
Hi,
Is there an update to this issue pr #29 has had it's last commit 24 days ago and doesn't store auth info in our DB backend.

**Comment by Aemilivs** [comment]
@Feynman43 are you working on this one?

**Comment by Feynman43** [comment]
@Aemilivs It was discussed with @skrabets and I should have an update from hi soon
