### ISSUE TITLE
Customize homepage UI template

### ISSUE THREAD

**Issue by allyune** [Aemilivs/2201-SAD-Bot-Trader#56]

**Comment by svarnypetr** [comment]
This issue is not connected to any PR/branch, what is its status and why is it still in review? What is the blocker?

**Comment by allyune** [comment]
> This issue is not connected to any PR/branch, what is its status and why is it still in review? What is the blocker?

This issue is related to the PR in UI module repo https://github.com/2201-Sad/Bot-Trader-Flask-GUI/pull/1, which I think has to be merged before opening PR for this issue (?)
